---
deployment:
  tasks:
    - export SOURCEPATH=/home/zxcbadzs/repositories/company_FE/dist/
    - export DEPLOYPATH=/home/zxcbadzs/public_html/
    - /bin/rsync -av --delete $SOURCEPATH $DEPLOYPATH
